### ISSUE TITLE
styles.css forces font HelveticaNeueLight, which does not display well.

### ISSUE THREAD

**Issue by iknowkungfoo** [KylinOLAP/Kylin#2]
Viewing the site in Chrome Version 37.0.2062.124 m (64-bit), MSIE 9.08 and FireFox 17.04 in Windows 7.

In /assets/css/styles.css, this section @ line 294

``` css
.main {
    position: relative;
    margin: 0;
    font-family: 'HelveticaNeueLight';
}
```

![kylin_helveticaneuelight_only](https://cloud.githubusercontent.com/assets/700256/4568167/9a2ac518-4f37-11e4-8f07-e18438f42929.jpg)

Overrides the default font-family @ line 52

``` css
body {
    font-size: 14px;
    font-size: 0.9375rem;
    font-family: 'open_sansregular', 'HelveticaNeueRegular', Arial, sans-serif;
    color: #666666;
    padding: 0;
}
```

Only a few characters are visible. By removing the font-family line under the <code>.main</code> definition, the browsers can select the proper replacement font.
![kylin_font_list](https://cloud.githubusercontent.com/assets/700256/4568168/9a2e51ec-4f37-11e4-93c9-e6115ffb2f4a.jpg)
